[package]
name = "DAY_23"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.6"
cortex-m-semihosting = "0.3"
panic-halt = "0.2"
stm32f103xx = "0.11"

[features]
# default = [] → when you do `cargo test` you get std + test
default = ["device"]
device = []
