[package]
name = "DAY_25"
version = "0.1.0"
edition = "2021"

[dependencies]
panic-halt   = "0.2"
avr-device   = { version = "0.3", features = ["atmega328p"] }
arduino-hal  = { version = "0.3", features = ["arduino_uno"] }

[profile.release]
opt-level = "s"
lto       = true
