[package]
name = "xrust_calclib"
version = "0.1.0"
edition = "2024"
description = "A Rust calculator library with floating‐point arithmetic and error handling"
license     = "Apache-2.0"
repository  = "https://github.com/62Xenon/ISPP60days-Challenge/tree/main/DAY_12/xrust_calclib"
readme      = "README.md"
keywords = ["calculator", "math", "arithmetic"]
categories = ["math"]

[features]
default = []
fancy   = []

[dependencies]
