[package]
name = "xrust_calclib"
version = "0.1.0"
edition = "2024"
description = "A Rust calculator library with floating‐point arithmetic and error handling"
license     = "Apache-2.0"
repository  = "https://github.com/62Xenon/ISPP60days-Challenge/tree/main/DAY_12/xrust_calclib"
readme      = "README.md"
exclude = [
    "/target/*",
    "*.png",
    "*.jpg",
    "*.mp4",
    "*.pdf",
    "/screenshots/*",
    "/media/*",
    "/large_data/*",
    "/.vscode/*",
    "*.zip",
    "*.tar.gz",
]

[features]
default = []
fancy   = []

[dependencies]
